import Head from 'next/head'
import Layout from '@/components/layout'
import NavBar from '@/components/navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ilham Prabaswara | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <NavBar />
        <main>
          <img className='mb-[25px] rounded' src='/ilham-avatar-large.png' />
          <p className='text-xl text-slate-900 leading-normal'>Hi! I’m <span className='font-semibold'>Ilham</span>. — a designer and developer based in Indonesia.</p>
          <p className='text-lg text-slate-600 leading-normal'>I started as a visual designer, but now I do a mix of everything from developing web to running e-commerce stores.</p>
          <p className='text-lg text-slate-600 leading-normal'>Technology that I use for frontend development is React.js, Next.js, Node.js, and any modern CSS framework & UI component.</p>
        </main>
      </Layout>
    </>
  )
}
